[project]
name = "releasor2000"
# binary = "releasor2000"  # defaults to project name
repo = "owner/releasor2000"
# version_command = "git describe --tags --abbrev=0"

[build]
command = "cargo build --release --target {target}"
artifact = "target/{target}/release/{binary}"
targets = [
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
]

[channels.github]
enabled = true

[channels.homebrew]
tap = "nakajima/homebrew-tap"
formula_name = "releasor2000"

# [channels.cargo]
crate_name = "releasor2000"

# [channels.curl]

# [channels.nix]
# flake_repo = "owner/nix-repo"
